from telethon import TelegramClient, events, sync
from telethon.tl.functions.channels import InviteToChannelRequest
from telethon.tl.functions.messages import ForwardMessagesRequest
from telethon.tl.types import MessageMediaDocument,InputFile,InputPeerChannel

from telebot import types
import time
import telebot
import openai
import schedule
import requests
import json
import asyncio
import random


API = "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"
openai.api_key = API
api_id = 4187951
api_hash = "0835315979fab595039ac5bf72dc218b"
client = TelegramClient("acc",api_id , api_hash)
bot = TelegramClient('bot_session', api_id=api_id, api_hash=api_hash).start(bot_token="6069743412:AAFiGLs_5rrWM7NkUf29Ef6Nw8gQ5RovshA")

tt = open("time.txt","w")
tt.write(str(time.time()))
tt.close()
ttt = open("time.txt","w")
ttt.write(str(time.time()))
ttt.close()

apprv = [1749293946,5854453255]
global limi
limi = 15

def change():
    F = open("members.txt","w")
    F.write("")
    F.close()


async def main():
    # اتصال به سرور تلگرام
    await client.start()
    
    @client.on(events.NewMessage(chats=[-1001852985107]))
    async def handler(event):
        if event.sender_id in [5940840757,5955887728,5778624772,6276768397]:
            if event.reply_to:
                yy = await client.get_messages(1852985107, ids=event.reply_to_msg_id)
                yyy = await client.get_entity(yy.from_id)
                yyyy = yyy.id
                if yyyy == 1749293946:
                    trgt = 1749293946
                    if event.media:
                        BAN = [["sex","s**"],["naked","n*k*d"],["nude","n*d*"],["beeg","b**g"],["dick","d***"],["pussy","pu***"],["ass","**s"],["boob","bo**"]]
                        cap = event.message.message.replace("@Midjourney42bot","").replace("generated by user","").replace("@DeliberateAIBot","").replace("@StableDiffusionRobot","")
                        for i in BAN:
                            cap = cap.replace(i[0],i[1])
                        capp = f'''عکس درخواستي!
'''+cap.split("\n")[0]+f'''
<a href="https://t.me/shwykh_Midjourney">ᴍɪᴅᴊᴏᴜʀɴᴇʏɪᴍᴀɢᴇ</a> ₪ <a href="https://t.me/xe_sk">ᴍᴇ</a> '''

                        photo = await event.download_media()
                        await bot.upload_file(photo)
                        await bot.send_file(trgt,photo,caption=capp, parse_mode='HTML',link_preview=False)
                    else:
                        cap = event.message.text.replace("@Midjourney42bot","").replace("generated by user","").replace("@DeliberateAIBot","").replace("@StableDiffusionRobot","").split("\n")
                        await bot.send_message(trgt,"خطا در درخواست عکس\n"+cap[-3].split(": ")[1]+"\n"+cap[-1])
                else:
                    pass
            else:
                pass
        else:
            pass


    @bot.on(events.NewMessage)
    async def get_response(message):
        if len(message.text) == 5:
            if message.text.lower() == "_help":
                await bot.send_message(message.chat.id, f'''دستورهای فعال:

_gpt hi
برای صبت با ربات
(فارسی✅)

_gmg nice blue chair
برای کشیدن عکس DALL-E
اين دستور فعلا غيرفعاله چون ميتونين از بهترش استفاده کنين

_gmpro nice blue chair
برای کشیدن عکس Midjourney
(فارسی✅)

_gmmax nice blue chair
برای کشیدن عکس Deliberate
(فعلا بهترين نسخه کشيدن عکس!)
(فارسی✅)

_gmmax nice blue chair
برای کشیدن عکس در StableDiffusion

_gmgvar
برای دریافت عکس های مشابه(کپشن عکس باشه)
اين دستور فعلا غيرفعاله

_gcartn
برای کارتونی کردن عکس(کپشن عکس باشه))
اين دستور فعلا غيرفعاله

_clear
ریست کردن محدودیت های اعضا(مخصوص ادمین)''', parse_mode="HTML",reply_to=message.id)
        if len(message.text) == 6:
            if message.text.lower() == "_clear" and False:
                if message.chat.id in apprv:
                    karbar = int(message.sender_id)
                    admnn = False
                    Ad = await getadmin(message.chat.id)
                    if karbar in Ad:
                        admnn = True
                    if admnn:
                        change()
                        await bot.send_message(message.chat.id, f'درخواست های اعضا ریست شدن', parse_mode="HTML",reply_to=message.id)
                    else:
                        await bot.send_message(message.chat.id, f'ادمین‌ها فقط مجاز به ریست کردن درخواست‌ها هستن', parse_mode="HTML",reply_to=message.id)
        if len(message.text) > 5:
            if message.text[:4].lower() == "_gpt" or message.text[:4].lower() == "_gmg" or message.text[:6].lower() == "_gmpro" or message.text[:6].lower() == "_gmmax" or message.text[:6].lower() == "_gmlol":
                if message.chat.id in apprv:
                    karbar = int(message.sender_id)
                    tt = open("time.txt","r")
                    qbl = float(tt.read().replace(" ","").replace("\n",""))
                    tt.close()
                    aln = float(time.time())
                    TTT = 30
                    if not aln-qbl > TTT:
                        ss = int(TTT-(aln-qbl))
                        pak = await bot.send_message(message.chat.id, f"بعد از {ss} ثانیه درخواست ارسال کنید", parse_mode="HTML",reply_to=message.id)
                        time.sleep(5)
                        await bot.delete_messages(message.chat.id,pak.id)
                    else:
                        tt = open("time.txt","w")
                        tt.write(str(time.time()))
                        tt.close()
                        F = open("members.txt","r")
                        f = F.readlines()
                        F.close()
                        ff = []
                        for i in f:
                            if len(i) > 1:
                                ff += [i.replace(" ","").replace("\n","").split(":")]
                        hast = False
                        for i in range(len(ff)):
                            if str(karbar) == ff[i][0]:
                                hast = True
                                o = i
                        if not hast:
                            F = open("members.txt","a+")
                            # دریافت اطلاعات عضویت فرستنده در گروه
                            karbar = int(message.sender_id)
                            admnn = False
                            #Ad = await getadmin(message.chat.id)
                            if True: #karbar in Ad:
                                admnn = True
                            # بررسی اینکه فرستنده جزو ادمین های گروه است یا خیر
                            if admnn:
                                mande = "نامحدود"
                                # فرستنده پیام ادمین گروه است
                                F.write(str(karbar)+":-1\n")
                            else:
                                mande = str(limi)
                                # فرستنده پیام ادمین گروه نیست
                                F.write(str(karbar)+":"+str(limi)+"\n")
                            F.close()
                        else:
                            if ff[o][1] == "0":
                                await bot.send_message(message.chat.id, f'تعداد فرصت استفاده شما از ربات تموم شده.برای استفاده بیشتر یا تا فردا صبر کن', parse_mode="HTML",reply_to=message.id)
                            elif int(ff[o][1]) >0 or int(ff[o][1]) == -1:
                                if not int(ff[o][1]) == -1:
                                    ###
                                    mande = str(int(ff[o][1])-1)
                                    ff[o][1] = str(int(ff[o][1])-1)
                                    F = open("members.txt","w")
                                    for i in ff:
                                        F.write(i[0]+":"+i[1]+"\n")
                                    F.close()
                                    ###
                                if int(ff[o][1]) == -1:
                                    mande = "نامحدود"
                        if True:
                            if message.text[:4].lower() == "_gpt":
                                bay = await bot.send_message(message.chat.id, "`⚗️Loading...`", parse_mode="md",reply_to=message.id)
                                mess = message.text[5:]
                                response = ""
                                if mess.startswith(">>>"):
                                    # Use Codex API for code completion
                                    response = openai.Completion.create(
                                    prompt=f'```\n{mess[3:]}\n```',
                                    temperature=0,
                                    max_tokens=4000,
                                    top_p=1,
                                    frequency_penalty=0,
                                    presence_penalty=0,
                                    stop=["\n", ">>>"]
                                    )
                                else:
                                    
                                    # Use GPT API for text completion
                                    # Check if the question is about code or not
                                    if "code" in mess.lower() or "python" in message.text.lower():
                                        # Use Codex API for code-related questions
                                        response = openai.Completion.create(
                                        engine="code-davinci-002",
                                        prompt=f'"""\n{mess}\n"""',
                                        temperature=0,
                                        max_tokens=4000,
                                        top_p=1,
                                        frequency_penalty=0,
                                        presence_penalty=0,
                                        stop=['"""']
                                        )
                                    else:
                                        RAFTAR = open("raftar.txt","r")
                                        raftar = RAFTAR.read().replace("\n","")
                                        RAFTAR.close()
                                        response = openai.ChatCompletion.create(
                                            model="gpt-3.5-turbo-0301", # engine="text-davinci-003",
                                            messages=[{"role": "system", "content": str(raftar)}, {"role": "user", "content": str(mess)}],
                                            temperature=0.3
                                        )
                                        
                                await bot.delete_messages(message.chat.id,bay.id)
                                await bot.send_message(message.chat.id, f'{response["choices"][0]["message"]["content"]}\n\n{mande} درخواست باقی مانده', parse_mode="HTML",reply_to=message.id)
                            elif message.text[:4].lower() == "_gmg" and False:
                                mess = message.text[5:]                                
                                image_url = [response['data'][0]['url']]
                                print(image_url)
                                photo_content = requests.get(image_url[0]).content
                                await bot.send_photo(chat_id=message.chat.id, photo=photo_content,reply_to=message.message_id,caption=f'{mande} درخواست باقی مانده')
                            elif message.text[:4].lower() == "_gmg":
                                await bot.send_message(message.chat.id, f'فعلا قابل استفاده نيست اين دستور.براي دستور بهتر، بنويسين _help', parse_mode="HTML",reply_to=message.id)
                            elif message.text[:6].lower() == "_gmpro" or message.text[:6].lower() == "_gmmax" or message.text[:6].lower() == "_gmlol":
                                mess = message.text[7:]
                                if message.text[:6].lower() == "_gmpro":
                                    mmm = mess+" @Midjourney42bot"
                                elif message.text[:6].lower() == "_gmmax":
                                    mmm = mess+" @DeliberateAIBot"
                                elif message.text[:6].lower() == "_gmlol":
                                    mmm = mess+" @StableDiffusionRobot"
                                await client.send_message(1852985107, message=mmm,reply_to=1135850)
                else:
                    await bot.send_message(message.chat.id, f"گروه تایید نشده", parse_mode="HTML")
    
    await client.run_until_disconnected()
    
if __name__ == '__main__':
    client.loop.run_until_complete(main())
    bot.infinity_polling(main())
    
